"""Init table

Revision ID: d1c30b15d8f5
Revises: 
Create Date: 2021-05-25 14:17:04.140340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1c30b15d8f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('time_slot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('start_at', sa.Integer(), nullable=False),
    sa.Column('end_at', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_time_slot_id'), 'time_slot', ['id'], unique=False)
    op.create_index(op.f('ix_time_slot_user_id'), 'time_slot', ['user_id'], unique=False)
    op.create_index('user_id__id', 'time_slot', ['user_id', 'id'], unique=False)
    op.create_index('user_id__id__end_at', 'time_slot', ['user_id', 'id', 'end_at'], unique=False)
    op.create_index('user_id__id__start_at__end_at', 'time_slot', ['user_id', 'start_at', 'end_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('user_id__id__start_at__end_at', table_name='time_slot')
    op.drop_index('user_id__id__end_at', table_name='time_slot')
    op.drop_index('user_id__id', table_name='time_slot')
    op.drop_index(op.f('ix_time_slot_user_id'), table_name='time_slot')
    op.drop_index(op.f('ix_time_slot_id'), table_name='time_slot')
    op.drop_table('time_slot')
    # ### end Alembic commands ###
